# .gitlab-ci.yml
#
# The environment variables can be configured at:
# https://gitlab.com/{YOU}/{YOUR_PROJECT}/-/settings/ci_cd
#
# Microsoft has some very useful Docker images for dev usage
# that include `pipx` and other python tools.
image: mcr.microsoft.com/vscode/devcontainers/python:3.9

# Enable Docker in Docker, and configure it.
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#docker-in-docker-with-tls-enabled
services:
  - docker:20-dind
variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

python_deploy:
  stage: deploy
  # Run only when commiting to "main"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  before_script:
    # Install the python-deploy cli
    - pipx install pd_cli~=1.0

  script:
    # Build the docker image
    - python-deploy build python-deploy:release
    # Deploy the docker image
    - python-deploy deploy python-deploy:release
