# .github/workflows/python_deploy.yml
#
# The environment variables can be configured at:
# https://github.com/{YOU}/{YOUR_PROJECT}/settings/secrets/actions

# Run only when commiting to "main"
on:
  push:
    branches:
      - main

jobs:
  python_deploy:
    # Microsoft has some very useful Docker images for dev usage
    # that include `pipx` and other python tools.
    container: mcr.microsoft.com/vscode/devcontainers/python:3.9
    name: Build and Deploy with PythonDeploy
    runs-on: ubuntu-latest
    env:
      PD_API_KEY: ${{ secrets.PD_API_KEY }}
      PD_APP_ID: ${{ secrets.PD_APP_ID }}
    steps:
      - uses: actions/checkout@v2

      # Install the python-deploy cli
      - run: pipx install "pd_cli~=1.0"

      # Build the docker image
      - run: python-deploy build python-deploy:release
      # Deploy the docker image
      - run: python-deploy deploy python-deploy:release
